version: '3.8'


services:
  postgres-restaurant:
    image: postgres:15.2-alpine
    restart: always
    ports:
      - "5431:5432"
    environment:
      POSTGRES_DB: restaurant
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  postgres-order:
    image: postgres:15.2-alpine
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: order
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres