management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

redis:
  service:
    prefix: CMN-SW:RDS
    ttl: 3000
    cacheable:
      ttl: 180
  server:
    address: localhost
    port: 6379
    cluster:
      nodes:
    password:
    environment: live
