spring:
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: ecomfmss@gmail.com
    password: vsqbngmpjwyjshya
#    mail giriş şifresi -> fmss2023Ecom
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
#  ldap:
#    urls: 'ldap://ldap.jumpcloud.com:389'
#    username: 'uid=mahoni,ou=Users,o=64346c9136393df65a68908f,dc=jumpcloud,dc=com'
#    password: 'deneme_1A'
jwt:
  secret: 'ecom-fmss'
  get:
    token:
      uri: '/authenticate'

redis:
  service:
    prefix: USR-SW:RDS
    ttl: 3000
    cacheable:
      ttl: 180
  server:
    address: localhost
    port: 6379
    cluster:
      nodes:
    password:
    environment: live
